config/routes.rb
Rails.application.routes.draw do
  resources :seats
  resources :actors
  resources :employees
  resources :movies
  resources :shows
  resources :cinemas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cinemas#index'
end

app/models/seat.rb
class Seat < ApplicationRecord
    self.per_page = 15
    belongs_to :show, class_name: 'Show'
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: [:show, :edit, :update, :destroy]

  # GET /seats
  # GET /seats.json
  def index
    if !Show.exists?(params[:show_id])
      flash[:warning] = "Please choose a valid show."
      redirect_to cinemas_url and return
    end
    @show = Show.find_by_id(params[:show_id])
    @seats = @show.seats
  end

  # GET /seats/1
  # GET /seats/1.json
  def show
  end

  # GET /seats/new
  def new
    @seat = Seat.new
  end

  # GET /seats/1/edit
  def edit
  end

  # POST /seats
  # POST /seats.json
  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        format.html { redirect_to @seat, notice: 'Seat was successfully created.' }
        format.json { render :show, status: :created, location: @seat }
      else
        format.html { render :new }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seats/1
  # PATCH/PUT /seats/1.json
  def update
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to @seat, notice: 'Seat was successfully updated.' }
        format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :edit }
        format.json { render json: @seat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.json
  def destroy
    @seat.destroy
    respond_to do |format|
      format.html { redirect_to seats_url, notice: 'Seat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seat
      @seat = Seat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seat_params
      params.require(:seat).permit(:show_id, :booked, :seat_number)
    end
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%= form_for(seat) do |f| %>
  <% if seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% seat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :booked %>
    <%= f.check_box :booked %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/edit.html.erb
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<div class='center'>
    <h1>Book Seat</h1>

    <%= render 'form', seat: @seat %>
    
    <%= link_to 'Back', cinemas_path %>
</div>

app/views/seats/index.html.erb
<p id="notice"><%= notice %></p>
<style>
.grid-container {
  display: grid;
  grid-template-columns: auto auto auto;
  background-color: #2196F3;
  padding: 10px;
}
.grid-item {
  background-color: rgba(255, 255, 255, 0.8);
  border: 1px solid rgba(0, 0, 0, 0.8);
  padding: 20px;
  font-size: 30px;
  text-align: center;
}
</style>

<h1>Seats</h1>
<div class="grid-container">
  <% @seats.each do |seat| %>
    <div class='grid-item'>
      <% if !seat.booked %>
        <%= link_to seat.seat_number, edit_seat_path(seat) %>
      <% else %>
        <%= seat.seat_number %>
      <% end %>
    </div>
  <% end %>
</div>
<br>

<%= link_to 'Back', cinemas_path %>

app/views/seats/new.html.erb
<h1>New Seat</h1>

<%= render 'form', seat: @seat %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Show:</strong>
  <%= @seat.show_id %>
</p>

<p>
  <strong>Booked:</strong>
  <%= @seat.booked %>
</p>

<p>
  <strong>Seat number:</strong>
  <%= @seat.seat_number %>
</p>

<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>