config/routes.rb
Rails.application.routes.draw do
  resources :seats
  resources :actors
  resources :employees
  resources :movies
  resources :shows
  resources :cinemas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cinemas#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
    self.per_page = 15
    belongs_to :cinema, class_name: "Cinema"
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    if !Cinema.exists?(params[:cinema_id])
      @employees = Employee.paginate(page: params[:page])
    else
      @cinema = Cinema.find_by_id(params[:cinema_id])
      @employees = @cinema.employees
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee.cinema_id = params[:cinema_id]
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :cinema_id, :age)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cinema_id %>
    <%= f.number_field :cinema_id %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>
<style>
.center {
  margin: auto;
  width: 50%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<div class = 'center'>
    <%= render 'form', employee: @employee %>

    <%= link_to 'Show', @employee %> |
    <%= link_to 'Back', employees_path %>
</div>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<style>
.center {
  margin: auto;
  width: 50%;
  border: 3px solid green;
  padding: 10px;
}
</style>

<div class='center'>
  <% if @cinema  %>
    <h1><%= @cinema.name %>:</h1>
  <% end %>
  <h1>Employees</h1>
  
  <table class="table table-hover", style="text-align:center; padding-left: 50px">
    <thead>
      <tr>
        <th>Name</th>
        <th>Cinema</th>
        <th>Age</th>
        <th colspan="2"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.cinema_id %></td>
          <td><%= employee.age %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  <% if @cinema  %>
    <%= link_to 'New Employee', new_employee_path(cinema_id: @cinema.id) %>
  <% else %>
    <%= link_to 'New Employee', new_employee_path %>
  <% end %>
  <%= link_to 'Back', cinemas_path %>
  <%= will_paginate(@employees) %>
</div>

app/views/employees/new.html.erb
<style>
.center {
  margin: auto;
  width: 50%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<div class='center'>
    <h1>New Employee</h1>

    <%= render 'form', employee: @employee %>

    <%= link_to 'Back', employees_path %>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Cinema:</strong>
  <%= @employee.cinema_id %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>