config/routes.rb
Rails.application.routes.draw do
  resources :seats
  resources :actors
  resources :employees
  resources :movies
  resources :shows
  resources :cinemas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cinemas#index'
end

app/models/show.rb
class Show < ApplicationRecord
    self.per_page = 15
    belongs_to :cinema, class_name: "Cinema"
    belongs_to :movie, class_name: "Movie"
    has_many :seats, class_name: "Seat"
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    if !Cinema.exists?(params[:cinema_id])
      flash[:warning] = "Please choose a valid cinema."
      redirect_to cinemas_url and return
    end
    @cinema = Cinema.find_by_id(params[:cinema_id])
    @shows = @cinema.shows
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
    @show.cinema_id = params[:cinema_id]
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:start_time, :end_time, :price, :movie_id, :cinema_id)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_for(show) do |f| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :movie_id %>
    <%= f.number_field :movie_id %>
  </div>
  
  <div class="field">
    <%= f.label :cinema_id %>
    <%= f.number_field :cinema_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/_form1.html.erb
<%= form_for(show) do |f| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid green;
  padding: 10px;
}
</style>

<div class='center'>
    <h1>Editing Show</h1>

    <%= render 'form1', show: @show %>
    
    <%= link_to 'Back', shows_path(cinema_id: @show.cinema_id) %>
</div>

app/views/shows/index.html.erb
<p id="notice"><%= notice %></p>
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<div class = 'center'>
  <h1><%= @cinema.name %>:</h1>
  <h1>Shows</h1>
  <table class="table table-hover", style="text-align:center; padding-left: 10px">
    <thead>
      <tr>
        <th>Movie</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @shows.each do |show| %>
        <% movie = show.movie%>
        <tr>
          <td><%= link_to movie.name, movie_url(id: movie.id, cinema_id: @cinema.id) %></td>
          <td><%= show.start_time %></td>
          <td><%= show.end_time %></td>
          <td><%= show.price %></td>
          <td><%= link_to 'Book', seats_url(show_id: show.id) %></td>
          <td><%= link_to 'Edit', edit_show_path(show) %></td>
          <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Show', new_show_path(cinema_id: @cinema.id) %>
  <%= link_to 'Back', cinemas_path %>
</div>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path(cinema_id: @show.cinema_id) %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @show.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @show.end_time %>
</p>

<p>
  <strong>Price:</strong>
  <%= @show.price %>
</p>

<p>
  <strong>Movie:</strong>
  <%= @show.movie_id %>
</p>

<p>
  <strong>Cinema:</strong>
  <%= @show.cinema_id %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>