config/routes.rb
Rails.application.routes.draw do
  resources :seats
  resources :actors
  resources :employees
  resources :movies
  resources :shows
  resources :cinemas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cinemas#index'
end

app/models/cinema.rb
class Cinema < ApplicationRecord
    self.per_page = 15
    has_many :shows, class_name: "Show", foreign_key: "cinema_id", dependent: :destroy
    has_many :movies, through: :shows
    has_many :employees, class_name: "Employee", foreign_key: "cinema_id", dependent: :nullify
end

app/controllers/cinemas_controller.rb
class CinemasController < ApplicationController
  before_action :set_cinema, only: [:show, :edit, :update, :destroy]

  # GET /cinemas
  # GET /cinemas.json
  def index
    @cinemas = Cinema.paginate(page: params[:page])
  end

  # GET /cinemas/1
  # GET /cinemas/1.json
  def show
  end

  # GET /cinemas/new
  def new
    @cinema = Cinema.new
  end

  # GET /cinemas/1/edit
  def edit
  end

  # POST /cinemas
  # POST /cinemas.json
  def create
    @cinema = Cinema.new(cinema_params)

    respond_to do |format|
      if @cinema.save
        format.html { redirect_to @cinema, notice: 'Cinema was successfully created.' }
        format.json { render :show, status: :created, location: @cinema }
      else
        format.html { render :new }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cinemas/1
  # PATCH/PUT /cinemas/1.json
  def update
    respond_to do |format|
      if @cinema.update(cinema_params)
        format.html { redirect_to @cinema, notice: 'Cinema was successfully updated.' }
        format.json { render :show, status: :ok, location: @cinema }
      else
        format.html { render :edit }
        format.json { render json: @cinema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cinemas/1
  # DELETE /cinemas/1.json
  def destroy
    @cinema.destroy
    respond_to do |format|
      format.html { redirect_to cinemas_url, notice: 'Cinema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cinema
      @cinema = Cinema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cinema_params
      params.require(:cinema).permit(:name, :address, :tel)
    end
end

app/helpers/cinemas_helper.rb
module CinemasHelper
end

app/views/cinemas/_form.html.erb
<%= form_for(cinema) do |f| %>
  <% if cinema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cinema.errors.count, "error") %> prohibited this cinema from being saved:</h2>

      <ul>
      <% cinema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :tel %>
    <%= f.text_field :tel %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cinemas/edit.html.erb
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<div class='center'>
    <h1>Editing Cinema</h1>
    <%= render 'form', cinema: @cinema %>

    <%= link_to 'Show', @cinema %> |
    <%= link_to 'Back', cinemas_path %>
</div>

app/views/cinemas/index.html.erb
<p id="notice"><%= notice %></p>
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid green;
  padding: 10px;
}
</style>

<div class='center'>
  <h1>Cinemas</h1>
  <table class="table table-hover", style="text-align:center; padding-left: 50px">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Tel</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @cinemas.each do |cinema| %>
        <tr>
          <td><%= link_to cinema.name, employees_url(cinema_id: cinema.id) %></td>
          <td><%= cinema.address %></td>
          <td><%= cinema.tel %></td>
          <td><%= link_to 'Schedule', shows_url(cinema_id: cinema.id) %></td>
          <td><%= link_to 'Edit', edit_cinema_path(cinema) %></td>
          <td><%= link_to 'Destroy', cinema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  
  <%= link_to 'New Cinema', new_cinema_path %>
  <%= will_paginate(@cinemas) %>
</div>

app/views/cinemas/new.html.erb
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid green;
  padding: 10px;
}
</style>
<div class = 'center'>
    <h1>New Cinema</h1>

    <%= render 'form', cinema: @cinema %>
    
    <%= link_to 'Back', cinemas_path %>
</div>

app/views/cinemas/show.html.erb
<p id="notice"><%= notice %></p>
<style>
.center {
  margin: auto;
  width: 60%;
  border: 3px solid green;
  padding: 10px;
}
</style>

<div class='center'>
  <p>
    <strong>Name:</strong>
    <%= @cinema.name %>
  </p>
  
  <p>
    <strong>Address:</strong>
    <%= @cinema.address %>
  </p>
  
  <p>
    <strong>Tel:</strong>
    <%= @cinema.tel %>
  </p>
  
  <%= link_to 'Edit', edit_cinema_path(@cinema) %> |
  <%= link_to 'Back', cinemas_path %>
</div>